Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2024-04, with the labels that each got.

#397 DEVOPS-000 - DDev PHP 8.2 and removinghooks
  .ddev/config.yaml
Labels: size/xs

#398 SDSS-359: number of people on initial load of view page
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
Labels: size/xs

#400 SDSS-1161: fixing the spacer error
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/spacer/_spacer.scss
Labels: size/xs

#402 SDSS-869 | @jdwjdwjdw | Adjust news list card
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/_news-list-card.scss
Labels: size/xs

#403 4.3.1
  .ddev/config.yaml
  CHANGELOG.md
  blt/src/Blt/Plugin/Commands/GryphonCommands.php
  docroot/profiles/sdss/sdss_profile/config/sdssrooms/config_split.patch.user.role.authenticated.yml
  docroot/profiles/sdss/sdss_profile/config/sdssrooms/user.role.authenticated.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_publication.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.paragraph.sdss_news_list_card.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.media.image.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.teaser.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.paragraph.sdss_news_list_card.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_article_journal.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_article_newspaper.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_book.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_other.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_thesis.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_event.su_event_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_event_series.su_event_series_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_news_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_person_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_publication.su_publication_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.sdss_news_list_card.su_news_card_button.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.sdss_news_list_card.su_news_card_headline.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.sdss_news_list_card.su_news_card_links.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_news_card_button.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_news_card_headline.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_news_card_links.yml
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.sdss_news_list_card.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/one_four_one/one-four-one.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/three_column/three-column.css
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/dist/islands/newsroom-menu.island.umd.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/components/hamburger.tsx
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/newsroom-menu.island.tsx
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/ckeditor.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/ckeditor.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/_news-list-card.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/spacer/_spacer.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_lists.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/block/block--menu-block--newsroom.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/components/news-list-card/field--paragraph--sdss-news-list-card.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/page.html.twig
Labels: patch, size/l

#404 Backtodev 4.3.2
  CHANGELOG.md
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
Labels: size/xs, patch

#406 SDSS-1249: button color fix
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/button/_button.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/card/_card-variants.scss
Labels: size/xs

#405 SDSS-1235: local footer config update
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.config_pages.stanford_local_footer.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.config_pages.stanford_local_footer.default.yml
  docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
Labels: size/xs

#408 SDSS-1252: Adding additional terms to contextual filter for people
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
Labels: size/xs

#411 SDSS-1265: Allow adding Basic Pages to Newsroom Menu from Edit Node form
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_page.field_menulink.yml
  docroot/profiles/sdss/sdss_profile/config/sync/node.type.stanford_page.yml
Labels: size/xs

#407 SDSS-252: Allow Events List paragraph to be filtered by multiple taxonomies
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_events.yml
Labels: size/s

#409 SDSS-1220: Add Media Mentions list display to News list paragraph
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_news.yml
Labels: size/m

#410 SDSS-1182: Retiring Magazine Topics
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.taxonomy_term.sdss_magazine_topics.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.search_indexing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.teaser.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_magazine_topics.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.node.su_sdss_magazine_topics.yml
  docroot/profiles/sdss/sdss_profile/config/sync/printable.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_sdss_magazine_topics.yml
  docroot/profiles/sdss/sdss_profile/config/sync/taxonomy.vocabulary.sdss_magazine_topics.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_builder.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_developer.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_editor.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_manager.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.rss_feeds.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.sdss_manage_content_bytype.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_news.yml
  docroot/profiles/sdss/sdss_profile/sdss_profile.install
Labels: size/s

#413 SDSS-1261: List of media mention spacing
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_news.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news/_news-list.scss
Labels: size/xs

#415 SDSS-1255: Uninstall earth_news_importer
  docroot/profiles/sdss/sdss_profile/sdss_profile.install
Labels: size/xs

#416 SDSS-1255: Earth News Importer uninstall update hook fixup
  docroot/profiles/sdss/sdss_profile/sdss_profile.install
Labels: size/xs

#417 SDSS-1271: Updated stanford_samlauth module
  composer.lock
  docroot/profiles/sdss/sdss_profile/config/sync/stanford_samlauth.settings.yml
Labels: size/s

#418 4.3.2
  CHANGELOG.md
  composer.lock
  docroot/profiles/sdss/sdss_profile/config/sync/stanford_samlauth.settings.yml
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
Labels: size/s, patch

#419 Backtodev 4.3.3
  CHANGELOG.md
  composer.lock
  docroot/profiles/sdss/sdss_profile/config/sync/stanford_samlauth.settings.yml
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
Labels: size/s, patch

#420 SDSS-1272: Enable search by title
  docroot/profiles/sdss/sdss_profile/config/sync/search_api.index.full_site_content.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.search.yml
Labels: size/xs

#412 SDSS-1263: Change link colors for all inline textual links
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news/_news-vertical-teaser.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_link.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
Labels: size/s, patch

#389 SDSS-1191: changed headline and dek for xl-md breakpoint
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news/_news-vertical-teaser.scss
Labels: size/xs

#424 SDSS-1262: Provision for techtransferfordefense
  blt/blt.yml
  docroot/sites/techtransferfordefense/blt.yml
  docroot/sites/techtransferfordefense/default.local.drush.yml
  docroot/sites/techtransferfordefense/default.services.yml
  docroot/sites/techtransferfordefense/default.settings.php
  docroot/sites/techtransferfordefense/settings.php
  docroot/sites/techtransferfordefense/settings/default.includes.settings.php
  docroot/sites/techtransferfordefense/settings/default.local.settings.php
  drush/sites/techtransferfordefense.site.yml
Labels: size/l

#425 SDSS-1269: Provisioned hph
  blt/blt.yml
  docroot/sites/hph/blt.yml
  docroot/sites/hph/default.local.drush.yml
  docroot/sites/hph/default.services.yml
  docroot/sites/hph/default.settings.php
  docroot/sites/hph/settings.php
  docroot/sites/hph/settings/default.includes.settings.php
  docroot/sites/hph/settings/default.local.settings.php
  drush/sites/hph.site.yml
Labels: size/l
