Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2024-07, with the labels that each got.

#453 SDSS-1302: Adding additional layout with widths baked in.
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_layout.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/three_column/three-column.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/two_column/two-column.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/two_column_larger_left/layout-paragraphs-sdss-two-column-larger-left.html.twig
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/two_column_larger_left/two-column-larger-left.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/two_column_larger_right/layout-paragraphs-sdss-two-column-larger-right.html.twig
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/two_column_larger_right/two-column-larger-right.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/sdss_layout_paragraphs.layouts.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/sdss_layout_paragraphs.libraries.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/TwoColumnEqual.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/TwoColumnLargerLeft.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/TwoColumnLargerRight.php
Labels: size/s

#465 SDSS-1276: News Sharing MVP
  docroot/profiles/sdss/sdss_profile/config/sync/config_ignore.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
  docroot/profiles/sdss/sdss_profile/config/sync/migrate_plus.migration.sdss_news_sharing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/migrate_plus.migration_group.sdss_news_sharing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.stanford_migrate_default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.stanford_migrate_sdss_news_sharing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.sdss_news_sharing.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.info.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.links.menu.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.permissions.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.routing.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.services.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/src/Form/NewsSharingSettingsForm.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/src/Overrides/ConfigOverrides.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/src/Plugin/migrate/process/AddBaseUrl.php
Labels: patch, size/l

#467 FIXUP - turn off readonly for news sharing form
  docroot/profiles/sdss/sdss_profile/config/sync/config_ignore.settings.yml
  docroot/sites/settings/global.settings.php
Labels: size/xs

#472 SDSS-1307 - sites file for esos
  docroot/sites/sites.php
Labels: size/xs

#468 SDSS-1342: Allow Event Lists to be filtered by focal areas
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_events.yml
Labels: size/xs

#473 SDSS-1135: Added publishing_date to source id for news sharing migration
  docroot/profiles/sdss/sdss_profile/config/sync/migrate_plus.migration.sdss_news_sharing.yml
Labels: size/xs
