Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2024-06, with the labels that each got.

#449 SDSS-1303: Provisioned cepp
  blt/blt.yml
  docroot/sites/cepp/blt.yml
  docroot/sites/cepp/default.local.drush.yml
  docroot/sites/cepp/default.services.yml
  docroot/sites/cepp/default.settings.php
  docroot/sites/cepp/settings.php
  docroot/sites/cepp/settings/default.includes.settings.php
  docroot/sites/cepp/settings/default.local.settings.php
  drush/sites/cepp.site.yml
Labels: size/l

#450 4.4.2
  CHANGELOG.md
  blt/blt.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_event.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.media.image.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/filter.format.stanford_html.yml
  docroot/profiles/sdss/sdss_profile/config/sync/filter.format.stanford_minimal_html.yml
  docroot/profiles/sdss/sdss_profile/config/sync/graphql.graphql_servers.graphql_compose_server.yml
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_card.yml
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_lists.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.rss_feeds.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/.nvmrc
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/dist/css/preview_paragraphs.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/package.json
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/scss/preview_paragraphs.scss
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/sdss_layout_paragraphs.libraries.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/webpack.config.js
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/yarn.lock
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/ckeditor.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
  docroot/sites/cepp/blt.yml
  docroot/sites/cepp/default.local.drush.yml
  docroot/sites/cepp/default.services.yml
  docroot/sites/cepp/default.settings.php
  docroot/sites/cepp/settings.php
  docroot/sites/cepp/settings/default.includes.settings.php
  docroot/sites/cepp/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/cepp.site.yml
Labels: size/xl, patch

#451 4.4.3
  CHANGELOG.md
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
Labels: size/xs, patch

#430 SDSS-1268: Removed the white option for row backgrounds
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Plugin/Layout/SdssLayoutParagraphBase.php
  docroot/profiles/sdss/sdss_profile/sdss_profile.install
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.react_behaviors.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
Labels: size/xs, patch

#448 SDSS-1305: Remove width options from SDSS layout paragraphs
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/one_column/one-column.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/two_column/two-column.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/OneColumn.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/OneFourOne.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/ThreeColumn.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/TwoColumn.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Plugin/Layout/SdssLayoutParagraphBase.php
Labels: size/xs

#414 SDSS-1201 | @jdwjdwjdw | Add 4 column card grid option for lists, adjust one-column layout, fixup load more issue
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/one_column/one-column.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/one_four_one/layout-paragraphs-sdss-one-four-one.html.twig
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/one_four_one/one-four-one.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/full-width.basic-page.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/js/scripts.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.libraries.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.react_behaviors.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.theme
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/basic-page/full-width.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/lists/_lists-paragraph.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/lists/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/_news-list-card.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_spotlight.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/webpack.config.js
Labels: size/s

#454 SDSS-1250: Provisioned sustainablesocieties
  blt/blt.yml
  docroot/sites/sustainablesocieties/blt.yml
  docroot/sites/sustainablesocieties/default.local.drush.yml
  docroot/sites/sustainablesocieties/default.services.yml
  docroot/sites/sustainablesocieties/default.settings.php
  docroot/sites/sustainablesocieties/settings.php
  docroot/sites/sustainablesocieties/settings/default.includes.settings.php
  docroot/sites/sustainablesocieties/settings/default.local.settings.php
  drush/sites/sustainablesocieties.site.yml
Labels: size/l

#456 SDSS-000 | @jdwjdwjdw | Full width specificity fixup
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/full-width.basic-page.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/basic-page/full-width.scss
Labels: size/xs

#455 SDSS-1308: Routine maintenance
  .github/workflows/tests.yml
  composer.json
  composer.lock
  docroot/profiles/sdss/sdss_profile/config/sync/autologout.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
  docroot/profiles/sdss/sdss_profile/config/sync/diff.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/editoria11y.configuration.yml
  docroot/profiles/sdss/sdss_profile/config/sync/graphql.graphql_servers.graphql_compose_server.yml
  docroot/profiles/sdss/sdss_profile/config/sync/jsonapi_extras.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/layout_paragraphs.modal_settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.stanford_decoupled_cron.yml
  docroot/profiles/sdss/sdss_profile/tests/codeception/functional/Content/EventsCest.php
  docroot/sites/default/default.settings.php
  docroot/sites/example.sites.php
Labels: size/l

#457 SDSS-1270: Deprecate and fully remove earth_news_importer
  composer.json
  composer.lock
  docroot/profiles/sdss/sdss_profile/config/sync/config_ignore.settings.yml
  tests/phpunit/example.phpunit.xml
Labels: size/xs

#458 SDSS-1296: Update SDSS profile installation
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/src/Plugin/InstallTask/SiteSettings.php
  docroot/profiles/sdss/sdss_profile/tests/src/Kernel/Plugin/InstallTask/SiteSettingsTest.php
  docroot/profiles/sdss/sdss_profile/tests/src/Unit/Plugin/HelpSection/ProfileConnectSectionTest.php
  docroot/profiles/sdss/sdss_profile/tests/src/Unit/Plugin/HelpSection/ProfileHelpSectionTest.php
  docroot/profiles/sdss/sdss_profile/tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
Labels: size/s, patch
