Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2024-05, with the labels that each got.

#422 SDSS-1266: Excluded Media Mention News from Site Search
  docroot/profiles/sdss/sdss_profile/config/sync/search_api.index.full_site_content.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.search.yml
Labels: size/xs

#426 SDSS-1218: Disabled page_cache module
  docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
  docroot/profiles/sdss/sdss_profile/sdss_profile.install
Labels: size/xs

#427 SDSS-1266: Excluded Media Mention News from Newsroom Search
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.news_research_search.yml
Labels: size/xs

#431 SDSS-1256: Actions cleanup and added matrix for testing
  .github/workflows/deploy_branch.yml
  .github/workflows/tests.yml
  docroot/sites/settings/global.settings.php
Labels: size/s

#433 SDSS-1286: Add CSS to stanford_profile_admin_theme and hide heading fields
  docroot/profiles/sdss/sdss_profile/themes/stanford_profile_admin_theme/css/admin.css
  docroot/profiles/sdss/sdss_profile/themes/stanford_profile_admin_theme/stanford_profile_admin_theme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/stanford_profile_admin_theme/stanford_profile_admin_theme.libraries.yml
Labels: size/xs, patch

#434 SDSS-1286: Fixup for banner heading choice.
  docroot/profiles/sdss/sdss_profile/themes/stanford_profile_admin_theme/css/admin.css
Labels: size/xs

#436 SDSS-1292: Changed specificity to the card h2 to match the stanford_profile_helper one.
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/card/_card.scss
Labels: size/xs

#440 SDSS-1290: Updated Github action CI release workflow
  .github/workflows/release.yml
  .github/workflows/tag_commits_to_main.yml
Labels: size/xs

#443 SDSS-1294: Fix logger syntax in installtask
  docroot/profiles/sdss/sdss_profile/src/Plugin/InstallTask/SiteSettings.php
Labels: size/xs

#444 4.4.1
  CHANGELOG.md
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/src/Plugin/InstallTask/SiteSettings.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
Labels: size/xs, patch

#421 SDSS-478: Fix to the wysiwyg spacing with section background colors
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/ckeditor.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
Labels: size/xs

#447 SDSS-1253: Unpoint techtransferfordefense from hackingfordefense
  docroot/sites/sites.php
Labels: size/xs

#428 SDSS-834: Hide non-display paragraphs values in Layout Paragraphs preview
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/.nvmrc
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/dist/css/preview_paragraphs.css
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/package.json
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/scss/preview_paragraphs.scss
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/sdss_layout_paragraphs.libraries.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/webpack.config.js
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/yarn.lock
Labels: size/xl

#432 SDSS-1288: Exclude Media Mentions from Explore More on News
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.default.yml
Labels: size/xs

#439 SDSS-1283: Changed default media image mode to full responsive
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_event.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.media.image.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/filter.format.stanford_html.yml
  docroot/profiles/sdss/sdss_profile/config/sync/filter.format.stanford_minimal_html.yml
  docroot/profiles/sdss/sdss_profile/config/sync/graphql.graphql_servers.graphql_compose_server.yml
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_card.yml
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_lists.yml
Labels: size/xs

#435 SDSS-1291: Label articles in RSS feed with external source
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.rss_feeds.yml
Labels: size/s, patch
