Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2024-03, with the labels that each got.

#394 SDSS-1072: Added role report blt command
  blt/src/Blt/Plugin/Commands/GryphonCommands.php
Labels: size/xs

#391 SDSS-869 | @jdwjdwjdw | Add News List Card paragraph type
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_publication.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.paragraph.sdss_news_list_card.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.teaser.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.paragraph.sdss_news_list_card.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_article_journal.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_article_newspaper.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_book.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_other.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.citation.su_thesis.su_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_event.su_event_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_event_series.su_event_series_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_news_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_person_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_publication.su_publication_components.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.sdss_news_list_card.su_news_card_button.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.sdss_news_list_card.su_news_card_headline.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.sdss_news_list_card.su_news_card_links.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_news_card_button.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_news_card_headline.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_news_card_links.yml
  docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.sdss_news_list_card.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/one_four_one/one-four-one.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/_news-list-card.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/components/news-list-card/field--paragraph--sdss-news-list-card.html.twig
Labels: size/m

#395 SDSS-1244: fine tuning a11y fix
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/block/block--menu-block--newsroom.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/page.html.twig
Labels: size/xs

#393 SDSS-637: Publication shared tags list and Teasers
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_lists.scss
Labels: size/s

#396 SDSS-1245: decoupled menu labels
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/dist/islands/newsroom-menu.island.umd.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/components/hamburger.tsx
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/newsroom-menu.island.tsx
Labels: size/xs
