Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2024-12, with the labels that each got.

#513 SDSS-1406: changed the light blue on the event circle to white
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/events/_events-list.scss
Labels: size/xs

#515 SDSS-1409: button color changes
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/dist/islands/newsroom-menu.island.umd.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/newsroom-menu.island.tsx
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/card/_card-variants.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/events/_events-list.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/_news-list-card.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news/_news.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_newsroom-menu--dropdown.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_link.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/variables/_colors.scss
Labels: size/s

#514 SDSS-1405 SDSS-1415: changes to section variants
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Plugin/Layout/SdssLayoutParagraphBase.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-border.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/variables/_colors.scss
Labels: size/xs

#519 SDSS-1418: Footerlinks are white
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/local-footer/_local-footer.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
Labels: size/xs

#516 SDSS-1422: remove blue navigation
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a.scss
Labels: size/xs

#522 SDSS-1429: mailto icon
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_link.scss
Labels: size/xs

#521 SDSS-1428: fix to the newsroom quote and editirial sidebar
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_callout_bgcolor_alt.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_sidebar_bgcolor_alt.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_callout.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_sidebar.scss
Labels: size/xs

#523 SDSS-1430: Primary btn fixup on green
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/local-footer/_local-footer.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
Labels: size/xs

#524 SDSS-1432: Right and top button margin in wyiwyg
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
Labels: size/xs

#525 SDSS-1431: Removed edit button from Stanford Person view.
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
Labels: size/s

#520 SDSS-1404: Quickstrike color updates
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_callout_bgcolor_alt.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_sidebar_bgcolor_alt.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Plugin/Layout/SdssLayoutParagraphBase.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/dist/islands/newsroom-menu.island.umd.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/newsroom-menu.island.tsx
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/card/_card-variants.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/events/_events-list.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/local-footer/_local-footer.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/_news-list-card.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news/_news.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_callout.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_newsroom-menu--dropdown.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_sidebar.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-border.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_link.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/variables/_colors.scss
Labels: size/s

#526 Release 4.7.1
  composer.json
  composer.lock
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_callout_bgcolor_alt.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_sidebar_bgcolor_alt.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Plugin/Layout/SdssLayoutParagraphBase.php
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/dist/islands/newsroom-menu.island.umd.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/newsroom-menu.island.tsx
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/card/_card-variants.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/events/_events-list.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/local-footer/_local-footer.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news-list-card/_news-list-card.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/news/_news.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_callout.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_newsroom-menu--dropdown.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/newsroom/_sidebar.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-border.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_link.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/variables/_colors.scss
Labels: size/m, patch

#528 SDSS-1426 | Update Gitpod setup documentation
  README.md
Labels: size/xs
