Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2024-08, with the labels that each got.

#464 SDSS-1185: Update caption text to be centered to the image and center aligned
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/theme/_caption.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/utilities/mixins/_typography.scss
Labels: size/xs

#478 SDSS-1337: Track news sharing imported content
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.search_indexing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.teaser.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_imported_news_sharing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.node.su_sdss_imported_news_sharing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/migrate_plus.migration.sdss_news_sharing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.sdss_news_sharing.yml
  docroot/profiles/sdss/sdss_profile/sdss_profile.install
Labels: size/s

#477 SDSS-1300: Featured Events This Week
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_event.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_event.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_event.su_sdss_featured.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.node.su_sdss_featured.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.events_this_week.yml
  docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Content/EventsCest.php
Labels: size/s

#481 SDSS-1321 | tweak mega menu background and height
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/dist/islands/main-menu.island.umd.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/main-menu.island.tsx
Labels: size/xs

#466 SDSS-1299: Add Explore More options and display to News
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.search_indexing.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.teaser.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_explore_more_picker.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.node.su_sdss_explore_more_picker.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.explore_more_news.yml
Labels: size/m

#480 SDSS-1358: Allow all editors to use Related Content field
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.node.su_sdss_related_content.yml
  docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Content/BasicPageCest.php
  docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Content/PublicationsCest.php
Labels: size/xs
