Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2025-09, with the labels that each got.

#639 SDSS-1550: SDSS Person Title Override Field Formatter Implementation
  .github/workflows/tests.yml
  blt/blt.yml
  docroot/profiles/sdss/sdss_profile/.github/ISSUE_TEMPLATE/bug_report.md
  docroot/profiles/sdss/sdss_profile/.github/ISSUE_TEMPLATE/feature_request.md
  docroot/profiles/sdss/sdss_profile/.github/auto-label.json
  docroot/profiles/sdss/sdss_profile/.github/pull_request_template.md
  docroot/profiles/sdss/sdss_profile/.github/workflows/back-to-dev.yml
  docroot/profiles/sdss/sdss_profile/.github/workflows/label.yml
  docroot/profiles/sdss/sdss_profile/.github/workflows/release.yml
  docroot/profiles/sdss/sdss_profile/.github/workflows/tests.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_person.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_person_title_override/README.md
  docroot/profiles/sdss/sdss_profile/modules/sdss_person_title_override/sdss_person_title_override.info.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_person_title_override/sdss_person_title_override.services.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_person_title_override/src/Plugin/Field/FieldFormatter/PersonTitleOverrideFormatter.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_person_title_override/src/Service/SdssPersonTitleService.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_person_title_override/tests/src/Unit/Plugin/Field/FieldFormatter/PersonTitleOverrideFormatterTest.php
  docroot/profiles/sdss/sdss_profile/modules/sdss_person_title_override/tests/src/Unit/Service/SdssPersonTitleServiceTest.php
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/.github/ISSUE_TEMPLATE/bug_report.md
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/.github/ISSUE_TEMPLATE/feature_request.md
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/.github/auto-label.json
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/.github/pull_request_template.md
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/.github/workflows/label.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/.github/workflows/release.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/.github/workflows/tests.yml
Labels: size/s, size/m, patch, size/l

#657 SDSS-0000: Update room reservation module to 8.1.22
  composer.json
  composer.lock
Labels: size/xs

#661 4.13.1
  CHANGELOG.md
  blt/blt.yml
  composer.json
  composer.lock
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
  docroot/sites/ese2025/blt.yml
  docroot/sites/ese2025/default.local.drush.yml
  docroot/sites/ese2025/default.services.yml
  docroot/sites/ese2025/default.settings.php
  docroot/sites/ese2025/settings.php
  docroot/sites/ese2025/settings/default.includes.settings.php
  docroot/sites/ese2025/settings/default.local.settings.php
  docroot/sites/sustainpathways/blt.yml
  docroot/sites/sustainpathways/default.local.drush.yml
  docroot/sites/sustainpathways/default.services.yml
  docroot/sites/sustainpathways/default.settings.php
  docroot/sites/sustainpathways/settings.php
  docroot/sites/sustainpathways/settings/default.includes.settings.php
  docroot/sites/sustainpathways/settings/default.local.settings.php
  drush/sites/ese2025.site.yml
  drush/sites/sustainpathways.site.yml
Labels: size/xl, patch

#667 SDSS-1565: Pull request template changes
  .github/pull_request_template.md
Labels: size/xs

#669 SDSS-1562: Point ssip.stanford.edu to sustainpathways site
  docroot/sites/sites.php
Labels: size/xs

#674 SDSS-1571: Reduce logo max height
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header.scss
Labels: size/s, size/xs
