Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2025-07, with the labels that each got.

#613 SDSS-1500: Add utility nav to sdss_subtheme
  docroot/profiles/sdss/sdss_profile/config/sync/block.block.sdss_subtheme_newsresearch.yml
  docroot/profiles/sdss/sdss_profile/config/sync/block.block.sdss_subtheme_utilitynavigation.yml
  docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Header/HeaderOptionsCest.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.theme
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a-utility-nav.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/utility-nav/_utility-nav.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/utility-nav/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/page.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/theme-settings.php
Labels: size/s, patch

#615 SDSS-1498: Quickstrike 2
  docroot/profiles/sdss/sdss_profile/config/sync/block.block.sdss_subtheme_newsresearch.yml
  docroot/profiles/sdss/sdss_profile/config/sync/block.block.sdss_subtheme_utilitynavigation.yml
  docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Header/HeaderOptionsCest.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.theme
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/assets/svg/close.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/assets/svg/hamburger-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/assets/svg/magnifying-glass-24px-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a-utility-nav.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-wrapper-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/main-navigation/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/multi-menu/_multi-menu-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/multi-menu/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/search/_search-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/search/_search.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/search/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/utility-nav/_utility-nav.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/utility-nav/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/page.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/theme-settings.php
Labels: patch, size/l

#617 Update room reservations module to latest version.
  composer.json
  composer.lock
Labels: size/xs

#620 SDSS-0000: Room reservation fixups
  composer.json
  composer.lock
Labels: size/xs

#621 SDSS-1498: Add min-height to masthead inner to prevent menu overlap
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a-hamburger.scss
Labels: size/xs

#622 SDSS-1539: Map sdss:webdev Workgroup to Administrator Role for All Sites
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.stanford_saml.su_simplesaml_roles.yml
  docroot/profiles/sdss/sdss_profile/sdss_profile.install
  docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Users/RoleMappingsCest.php
Labels: size/xs

#626 SDSS-1542: Update events XML feed
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.events_feeds.yml
Labels: size/xs

#627 SDSS-1530: Remove cron job step from provision documentation
  docs/new-site-provision.md
Labels: size/xs

#629 SDSS-1502: Deprecate and remove sdss_main_site_subtheme from codebase
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/.nvmrc
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/TERMSOFUSE.txt
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/dist/css/sdss_main_site_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/favicon.ico
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/package.json
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.libraries.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.theme
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/.gitkeep
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/caret-closed-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/caret-down-green.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/caret-opened-green.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/close.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/hamburger-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/magnifying-glass-24px-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/sdss-footer-lockup.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/masthead/_header.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/masthead/_wrapper.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/masthead/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/multi-menu/_main-navigation.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/multi-menu/_multi-menu.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/multi-menu/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/search/_search.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/search/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/utility-nav/_utility-nav.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/utility-nav/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/config/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_buttons.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_centered-column.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_link-icon.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_links-news.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_links.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_screen-margins.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_typography.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_breakpoints.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_grid.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_magic-numbers.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_screen-margins.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_typography.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/templates/page.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/webpack.config.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/yarn.lock
Labels: size/xl, patch

#630 Updated views_taxonomy_term_name_depth module and multiple value patch
  composer.lock
  patches/contrib/views_taxonomy_term_name_depth-mr-2.patch
Labels: size/s, patch

#632 Backtodev 4.12.2
  CHANGELOG.md
  composer.lock
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
  patches/contrib/views_taxonomy_term_name_depth-mr-2.patch
Labels: size/s, patch

#614 SDSS-1536: Streamline Lockup Settings and Fix Theme Configuration Bugs
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.config_pages.lockup_settings.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.lockup_settings.su_intro.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.lockup_settings.su_line_1.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.lockup_settings.su_line_2.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.lockup_settings.su_line_3.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.lockup_settings.su_line_4.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.lockup_settings.su_line_5.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.lockup_settings.su_lockup_enabled.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.lockup_settings.su_lockup_options.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.config_pages.su_intro.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.config_pages.su_line_2.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.config_pages.su_line_3.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.config_pages.su_line_4.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.config_pages.su_line_5.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.config_pages.su_lockup_enabled.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.config_pages.su_lockup_options.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/jumpstart_ui/templates/components/lockup/lockup.ui_patterns.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/src/Config/ConfigOverrides.php
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/stanford_profile_helper.module
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/stanford_profile_helper.services.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/tests/src/Unit/Config/ConfigOverridesTest.php
  docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/img/sdss-lock-up-color.png
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/assets/img/sdss-lock-up-color.png
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/lockup/_lockup.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/block/block--system-branding-block.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/components/local-footer/pattern-localfooter.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/theme-settings.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/webpack.config.js
  docroot/profiles/sdss/sdss_profile/themes/stanford_basic/config/install/stanford_basic.settings.yml
  docroot/profiles/sdss/sdss_profile/themes/stanford_basic/config/schema/stanford_basic.schema.yml
  docroot/profiles/sdss/sdss_profile/themes/stanford_basic/tests/behat/features/brandbar.feature
  docroot/profiles/sdss/sdss_profile/themes/stanford_basic/tests/behat/features/globalfooter.feature
  docroot/profiles/sdss/sdss_profile/themes/stanford_basic/tests/behat/features/lockup.feature
  docroot/profiles/sdss/sdss_profile/themes/stanford_basic/theme-settings.php
Labels: size/l

#633 SDSS-1546: Fix full-width background for three and two-column layouts at large breakpoint
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/dist/css/component/node/stanford_page.layout.full-width.css
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/lib/scss/component/node/stanford_page.layout.full-width.scss
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/package.json
Labels: size/xs

#634 SDSS-1541: Routine maintenance
  composer.lock
Labels: size/s

#635 SDSS-1523: Add aria-label to the video banner play and pause button
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/js/scripts.js
Labels: size/xs
