Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2025-01, with the labels that each got.

#527 SDSS-1400: December 2024 maintenance and updates.
  CHANGELOG.md
  composer.json
  composer.lock
  config/envs/local/ultimate_cron.job.dblog_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/environment_indicator.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/metatag.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/search_api.index.full_site_content.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.content_lock_timeout_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.fast_404_generator_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.field_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.field_encrypt_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.file_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.google_analytics_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.layout_builder_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.node_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.scheduler_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.search_api_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.simple_oauth_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.stanford_decoupled_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.stanford_events_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.stanford_fields_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.stanford_profile_helper_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.system_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.ultimate_cron_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.xmlsitemap_cron.yml
  docroot/profiles/sdss/sdss_profile/config/sync/ultimate_cron.job.xmlsitemap_engines_cron.yml
  patches/contrib/field_encrypt-mr-31.patch
Labels: size/l

#530 SDSS-1439 | Provisioned energy-transition-analysis.stanford.edu.
  blt/blt.yml
  docroot/sites/energy_transition_analysis/blt.yml
  docroot/sites/energy_transition_analysis/default.local.drush.yml
  docroot/sites/energy_transition_analysis/default.services.yml
  docroot/sites/energy_transition_analysis/default.settings.php
  docroot/sites/energy_transition_analysis/settings.php
  docroot/sites/energy_transition_analysis/settings/default.includes.settings.php
  docroot/sites/energy_transition_analysis/settings/default.local.settings.php
  drush/sites/energy_transition_analysis.site.yml
Labels: size/l

#531 Update su-sws/blt-sws
  composer.lock
  docroot/sites/default/default.settings.php
Labels: size/xs

#534 SDSS-1391: Add 'www' to Stanford University brand bar link
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/jumpstart_ui/dist/templates/decanter/components/brand-bar/brand-bar.twig
Labels: size/xs

#529 SDSS-1427: Fix SDSS News Sharing migration item_selector configuration
  docroot/profiles/sdss/sdss_profile/config/sync/migrate_plus.migration.sdss_news_sharing.yml
Labels: size/xs

#538 SDSS-1333: Move SDSS News Sharing Settings to Configuration->Importers
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.links.menu.yml
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.routing.yml
Labels: size/xs, patch
