Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2025-06, with the labels that each got.

#591 Added database and branch clean-up workflows
  .github/workflows/acquia_cleanup.yml
  .github/workflows/copy_dbs_to_staging.yml
  blt/src/Blt/Plugin/Commands/GryphonAcquiaApiCommands.php
Labels: size/s, patch

#600 SDSS-1347: Add Workgroup Tagging settings to config_readonly whitelist
  docroot/sites/settings/global.settings.php
Labels: size/xs

#601 SDSS-1524, SDSS-1525, SDSS-1526: Provisioned fuels, gese, and sunproject
  blt/blt.yml
  docroot/sites/fuels/blt.yml
  docroot/sites/fuels/default.local.drush.yml
  docroot/sites/fuels/default.services.yml
  docroot/sites/fuels/default.settings.php
  docroot/sites/fuels/settings.php
  docroot/sites/fuels/settings/default.includes.settings.php
  docroot/sites/fuels/settings/default.local.settings.php
  docroot/sites/gese/blt.yml
  docroot/sites/gese/default.local.drush.yml
  docroot/sites/gese/default.services.yml
  docroot/sites/gese/default.settings.php
  docroot/sites/gese/settings.php
  docroot/sites/gese/settings/default.includes.settings.php
  docroot/sites/gese/settings/default.local.settings.php
  docroot/sites/sunproject/blt.yml
  docroot/sites/sunproject/default.local.drush.yml
  docroot/sites/sunproject/default.services.yml
  docroot/sites/sunproject/default.settings.php
  docroot/sites/sunproject/settings.php
  docroot/sites/sunproject/settings/default.includes.settings.php
  docroot/sites/sunproject/settings/default.local.settings.php
  drush/sites/fuels.site.yml
  drush/sites/gese.site.yml
  drush/sites/sunproject.site.yml
Labels: size/xl

#604 SDSS-856: Add field to conditionally hide the editorial sidebar title
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.paragraph.editorial_sidebar.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.paragraph.editorial_sidebar.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_hide_sidebar_title.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_sidebar_title.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_hide_sidebar_title.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/components/newsroom-sidebar/paragraph--editorial-sidebar.html.twig
Labels: size/xs

#605 SDSS-1499: Add option and styles to SDS theme to use Desktop Hamburger menu
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.theme
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/assets/svg/close.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/assets/svg/hamburger-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/assets/svg/magnifying-glass-24px-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-option-a.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header-wrapper-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/main-navigation/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/multi-menu/_multi-menu-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/multi-menu/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/search/_search-hamburger.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/search/_search.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/search/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/theme-settings.php
Labels: size/l

#606 SDSS-0000: Update stanford_earth_r25 room reservation module to 8.1.15.
  composer.json
  composer.lock
Labels: size/xs

#611 SDSS-1530: Add drupal cron and drupal cron scheduler commands and scripts
  blt/src/Blt/Plugin/Commands/GryphonCommands.php
  blt/src/Blt/Plugin/Commands/SdssCronCommands.php
  scripts/README.md
  scripts/run-drupal-cron-scheduler.sh
  scripts/run-drupal-cron.sh
Labels: size/s
