Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2025-04, with the labels that each got.

#566 SDSS-1472: Routine maintenance
  composer.json
  composer.lock
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_event.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_person.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_policy.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
  docroot/profiles/sdss/sdss_profile/config/sync/extlink.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.stanford_global_message.su_global_msg_message.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_f_intro.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.stanford_super_footer.su_super_foot_text.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_news_banner_caption.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_news_dek_long.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_person_location_address.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_person_research.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_person_scholarly_interests.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_alt_bio.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_alt_title.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_research_state.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_author_title.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_quote.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_sidebar_body.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_sidebar_title.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.stanford_accordion.su_accordion_body.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.stanford_banner.su_sdss_banner_caption.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.stanford_schedule.su_schedule_description.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.stanford_wysiwyg.su_wysiwyg_text.yml
  docroot/profiles/sdss/sdss_profile/config/sync/simple_oauth.settings.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_events/stanford_events.info.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_news/stanford_news.info.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_person/stanford_person.info.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/lib/scss/base/stanford_profile_styles.scss
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/package.json
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/stanford_profile_styles.info.yml
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/stanford_profile_styles.module
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/webpack.config.js
  docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_profile_styles/yarn.lock
  docroot/profiles/sdss/sdss_profile/tests/codeception/functional/Contrib/ExtLinkCest.php
  docroot/profiles/sdss/sdss_profile/tests/src/Kernel/EventSubscriber/EventSubscriberTest.php
Labels: size/xl, patch

#560 SDSS-1445: Use the Authenticated role to render Search API results
  docroot/profiles/sdss/sdss_profile/config/sync/search_api.index.full_site_content.yml
Labels: size/xs

#572 SDSS-460: Enable the URL alias field on News, Events, and People node forms
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_event.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_news.default.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_person.default.yml
Labels: size/xs

#460 SDSS-586: Created Related Content list displays for People, News and Events
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.related_content.yml
Labels: size/l

#573 SDSS-1496: Add more filters to Past Events list paragraph
  docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_events.yml
Labels: size/xs

#574 SDSS-000: Implement http_cache_control module
  composer.json
  composer.lock
  config/envs/dev/config_split.patch.seckit.settings.yml
  config/envs/dev/purge.plugins.yml
  config/envs/dev/seckit.settings.yml
  config/envs/dev/stage_file_proxy.settings.yml
  config/envs/prod/config_split.patch.seckit.settings.yml
  config/envs/prod/config_split.patch.system.performance.yml
  config/envs/prod/http_cache_control.settings.yml
  config/envs/prod/purge.plugins.yml
  config/envs/prod/seckit.settings.yml
  config/envs/stage/config_split.patch.seckit.settings.yml
  config/envs/stage/config_split.patch.system.performance.yml
  config/envs/stage/http_cache_control.settings.yml
  config/envs/stage/purge.plugins.yml
  config/envs/stage/seckit.settings.yml
  config/envs/stage/stage_file_proxy.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/config_split.config_split.dev.yml
  docroot/profiles/sdss/sdss_profile/config/sync/config_split.config_split.prod.yml
  docroot/profiles/sdss/sdss_profile/config/sync/config_split.config_split.stage.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.sdss_reviewer.yml
Labels: size/s

#576 Backtodev 4.10.1
  CHANGELOG.md
  docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
Labels: size/xs, patch

#577 Add filter_format dependencies
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_news_banner_caption.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_news_dek_long.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_alt_bio.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_alt_title.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_research_state.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_author.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_author_title.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_quote.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_sidebar_body.yml
  docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_sidebar_title.yml
Labels: size/xs

#578 Import field configurations with allowed_formats
  docroot/profiles/sdss/sdss_profile/sdss_profile.install
Labels: size/xs

#579 Point integrative-design long alias to extreme energy efficiency site
  docroot/sites/sites.php
Labels: size/xs
