Repository SU-SWS/ace-sdssgryphon, pull requests merged in 2025-02, with the labels that each got.

#540 SDSS-1332 | Enhance help text for News Sharing
  docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/src/Form/NewsSharingSettingsForm.php
Labels: size/xs

#518 SDSS-1412: Added Utility Navigation menu configuration
  docroot/profiles/sdss/sdss_profile/config/sync/system.menu.utility-navigation.yml
Labels: size/xs

#539 SDSS-1411: Add sdss_main_site_subtheme and extend hamburger breakpoint to all breakpoints in theme
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/.nvmrc
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/TERMSOFUSE.txt
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/dist/css/ckeditor.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/dist/css/sdss_main_site_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/favicon.ico
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/js/scripts.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/package.json
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.libraries.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.theme
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/.gitkeep
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/caret-closed-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/caret-down-green.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/caret-opened-green.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/close.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/hamburger-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/magnifying-glass-24px-black.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/assets/svg/sdss-footer-lockup.svg
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/ckeditor.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/masthead/_header.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/masthead/_wrapper.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/masthead/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/multi-menu/_main-navigation.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/multi-menu/_multi-menu.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/multi-menu/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/search/_search.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/search/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/config/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_background-colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_buttons.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_centered-column.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_cta.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_link-icon.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_links-news.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_links.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_screen-margins.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_typography.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_breakpoints.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_grid.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_magic-numbers.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_screen-margins.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/_typography.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/variables/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/theme-settings.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/webpack.config.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/yarn.lock
Labels: size/xl, patch

#543 SDSS-1413: Add and style Utility Nav region for sdss_main_site_subtheme and make header logo clickable
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/dist/css/ckeditor.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/dist/css/sdss_main_site_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/js/scripts.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.libraries.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/sdss_main_site_subtheme.theme
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/ckeditor.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/masthead/_header.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/multi-menu/_main-navigation.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/multi-menu/_multi-menu.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/search/_search.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/utility-nav/_utility-nav.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/utility-nav/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/config/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_background-colors.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/_cta.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/utilities/mixins/index.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/templates/page.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/theme-settings.php
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/webpack.config.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.libraries.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.react_behaviors.yml
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/theme-settings.php
  docroot/profiles/sdss/sdss_profile/themes/stanford_basic/stanford_basic.info.yml
  docroot/profiles/sdss/sdss_profile/themes/stanford_basic/stanford_basic.libraries.yml
Labels: size/m, patch

#544 SDSS-1457: Change local footer color
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/package.json
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/local-footer/_local-footer.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/yarn.lock
Labels: size/xl

#545 SDSS-1461: Quickstrike QA tweaks
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/dist/css/sdss_main_site_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/masthead/_wrapper.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/src/scss/components/utility-nav/_utility-nav.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/js/scripts.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/banner/_banner.scss
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/header/_header.scss
Labels: size/xs

#546 SDSS-1461: Quickstrike tweaks round 2
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/dist/css/sdss_subtheme.css
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/js/scripts.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/banner/_banner.scss
Labels: size/xs

#547 SDSS-1450: 4.7.4 Routine Maintenance
  composer.json
  composer.lock
  docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.teaser.yml
  docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
  docroot/profiles/sdss/sdss_profile/config/sync/editoria11y.settings.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.authenticated.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_builder.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_developer.yml
  docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_manager.yml
Labels: size/l

#552 SDSS-1466: Restore Newsroom menu for sdss_main_site_subtheme
  docroot/profiles/sdss/sdss_profile/modules/sdss_profile_helper/sdss_profile_helper.module
  docroot/profiles/sdss/sdss_profile/themes/sdss_main_site_subtheme/templates/page.html.twig
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/dist/islands/newsroom-menu.island.umd.js
  docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/decoupled-menu/src/newsroom-menu.island.tsx
Labels: size/xs
